name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Lint all packages
      run: pnpm run lint

    - name: Type check all packages
      run: pnpm run type-check

    - name: Build all packages
      run: pnpm run build

    - name: Test rules engine
      run: pnpm --filter @majong/rules run test

  e2e:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Install Playwright
      run: pnpm --filter @majong/web exec playwright install --with-deps

    - name: Build dependencies
      run: |
        pnpm --filter @majong/rules run build
        pnpm --filter @majong/ui run build

    - name: Build web app
      run: pnpm --filter @majong/web run build

    - name: Start web app
      run: pnpm --filter @majong/web run preview &
      
    - name: Wait for server
      run: |
        timeout 30 bash -c 'until curl -f http://localhost:4173/majong/; do sleep 1; done'

    - name: Run Playwright tests
      run: pnpm --filter @majong/web run test:e2e

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-results
        path: apps/web/test-results/